version: '3'

services:
  docmost:
    image: docmost/docmost:latest
    container_name: docmost
    depends_on:
      - db
      - redis
    env_file:
      - /data/docmost/docmost.env
    environment:
      APP_URL: 'https://docmost.irotnep.net'
      REDIS_URL: 'redis://redis:6379'
    ports:
      - "4000:3000"
    restart: unless-stopped
    volumes:
      - /data/docmost/app:/app/data/storage

  db:
    image: postgres:16-alpine
    container_name: docmost-db
    env_file:
      - /data/docmost/docmost.env
    environment:
      POSTGRES_DB: docmost
      POSTGRES_USER: docmost
    restart: unless-stopped
    volumes:
      - /data/docmost/db:/var/lib/postgresql/data

  redis:
    image: redis:7.2-alpine
    container_name: docmost-redis
    restart: unless-stopped
    volumes:
      - redis:/data


volumes:
  redis:
