# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "ehci_pci" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "zpool/root";
      fsType = "zfs";
    };

  fileSystems."/home" =
    { device = "zpool/home";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    { device = "zpool/nix";
      fsType = "zfs";
    };

  fileSystems."/data" =
    { device = "zpool/data";
      fsType = "zfs";
    };

  fileSystems."/boot1" =
    { device = "/dev/disk/by-uuid/599B-943A";
      fsType = "vfat";
    };

  fileSystems."/boot2" =
    { device = "/dev/disk/by-uuid/59A4-41E3";
      fsType = "vfat";
    };

  fileSystems."/boot3" =
    { device = "/dev/disk/by-uuid/59AB-25DF";
      fsType = "vfat";
    };

  fileSystems."/boot4" =
    { device = "/dev/disk/by-uuid/59B6-E963";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/437820a4-ba85-437e-8932-e8a5055e90c2"; }
      { device = "/dev/disk/by-uuid/21abbbee-fb6c-46cc-ae33-7bc2a118b192"; }
      { device = "/dev/disk/by-uuid/9a19f856-b733-4c38-83d4-6556e4183f83"; }
      { device = "/dev/disk/by-uuid/3e0baae8-9948-48e3-b1d1-5bd8420025f1"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno2.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
